#!/usr/bin/env python3
"""Export approved public case fields from canonical case-state records.

The exporter deliberately excludes private intake, admin, customer, and reviewer
data. Generated files are deterministic: no wall-clock timestamp is embedded.
"""

from __future__ import annotations

import html
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BASE_URL = "https://structurevidence.org"


def load(relative: str) -> dict:
    return json.loads((ROOT / relative).read_text(encoding="utf-8"))


def write_json(relative: str, value: object) -> None:
    content = json.dumps(value, ensure_ascii=False, indent=2) + "\n"
    for path in [ROOT / relative, ROOT / "docs" / relative]:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def yaml_quote(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    return json.dumps(str(value), ensure_ascii=False)


def write_case_yaml(slug: str, case: dict) -> None:
    fields = [
        ("case_id", case["case_id"]),
        ("title", case["title"]),
        ("canonical_url", case["canonical_url"]),
        ("question", case["question"]),
        ("current_state", case["current_state"]),
        ("as_of", case["as_of"]),
        ("last_material_change", case["last_material_change"]),
        ("evidence_count", len(case["evidence"])),
        ("counter_evidence_count", len(case["counter_evidence"])),
        ("unknown_count", len(case["unknowns"])),
    ]
    text = "# Generated by scripts/export_public_records.py; do not edit manually.\n"
    text += "\n".join(f"{key}: {yaml_quote(value)}" for key, value in fields) + "\n"
    for path in [ROOT / "cases" / slug / "case.yaml", ROOT / "docs" / "cases" / slug / "case.yaml"]:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")


def evidence_html(case: dict, evidence: dict) -> str:
    evidence_id = evidence["evidence_id"]
    canonical = f"{BASE_URL}/e/{evidence_id}/"
    title = evidence["title"]
    dataset = {
        "@context": "https://schema.org",
        "@type": "Dataset",
        "name": title,
        "description": evidence["supports"],
        "dateModified": evidence["observed_date"],
        "url": canonical,
        "creator": {"@type": "Organization", "name": "StructEvidence", "url": f"{BASE_URL}/"},
        "isPartOf": case["canonical_url"],
    }
    citation = (
        f'StructEvidence. "{title}." Evidence ID: {evidence_id}. '
        f"Accessed YYYY-MM-DD. {canonical}"
    )
    return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(title)} | StructEvidence</title><meta name="description" content="{html.escape(evidence['supports'])}">
<link rel="canonical" href="{canonical}"><link rel="stylesheet" href="/assets/product.css?v=20261001-gravity">
<script type="application/ld+json">{json.dumps(dataset, ensure_ascii=False)}</script></head>
<body class="product-site"><a class="skip-link" href="#main">Skip to content</a>
<header class="product-header"><nav class="product-nav" aria-label="Primary navigation"><a class="product-brand" href="/"><span>SE</span><strong>StructEvidence</strong></a><div class="product-links"><a href="/cases/">Cases</a><a href="/changes/">Changes</a><a href="/method.html">Method</a></div></nav></header>
<main class="product-main" id="main"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">StructEvidence</a><span>›</span><a href="{case['canonical_url'].replace(BASE_URL, '')}">{html.escape(case['title'])}</a><span>›</span><span aria-current="page">Evidence</span></nav>
<section class="page-hero citation-hero"><p class="eyebrow">Evidence record · {html.escape(evidence_id)}</p><h1>{html.escape(title)}</h1><p class="lead">Atomic public evidence record linked to its parent case and source boundary.</p></section>
<section class="product-section citation-section"><article class="evidence-record"><dl class="record-grid">
<div><dt>EVIDENCE ID</dt><dd>{html.escape(evidence_id)}</dd></div><div><dt>PARENT CASE</dt><dd><a href="{case['canonical_url'].replace(BASE_URL, '')}">{html.escape(case['title'])}</a></dd></div>
<div><dt>SOURCE</dt><dd><a href="{html.escape(evidence['source_url'])}">{html.escape(evidence['publisher'])}</a></dd></div><div><dt>SOURCE DATE</dt><dd>{html.escape(evidence['source_date'])}</dd></div>
<div><dt>OBSERVED DATE</dt><dd>{html.escape(evidence['observed_date'])}</dd></div><div><dt>CLASSIFICATION</dt><dd>{html.escape(evidence['classification'])}</dd></div>
<div><dt>WHAT IT SUPPORTS</dt><dd>{html.escape(evidence['supports'])}</dd></div><div><dt>WHAT IT DOES NOT ESTABLISH</dt><dd>{html.escape(evidence['does_not_establish'])}</dd></div>
<div><dt>ACCESSIBILITY</dt><dd>Public URL reviewed at the stated knowledge boundary.</dd></div><div><dt>SEARCH PROVENANCE</dt><dd><a href="{case['canonical_url'].replace(BASE_URL, '')}#search-provenance">Parent-case provenance</a></dd></div>
</dl><div class="citation-box"><p class="field-label">Suggested citation</p><p>{html.escape(citation)}</p><button class="button small" type="button" data-copy-citation data-citation="{html.escape(citation, quote=True)}">Copy citation</button> <a href="index.json">Machine-readable JSON</a><span data-citation-status role="status" aria-live="polite"></span></div></article></section></main>
<footer class="product-footer"><div class="product-wrap footer-grid"><strong>StructEvidence</strong><a href="{case['canonical_url'].replace(BASE_URL, '')}">Parent case</a><a href="/cases/submit-evidence/?case={case['case_id']}">Challenge this record</a><span>Evidence is bounded; limits remain part of the citation.</span></div></footer><script src="/assets/product.js?v=20261001-gravity"></script></body></html>'''


def build_cases() -> dict[str, dict]:
    dc = load("cases/800vdc/state-v0.1.json")
    sodium = load("cases/sodium-ion-bess/state-v0.1.json")
    dc_evidence = [{
        "evidence_id": "L1-EV-CML-PDRE-001-FIELD-DEPLOYMENT-001",
        "title": "800V DC Data Center Power Architecture: Field Deployment Evidence",
        "source_url": "https://www.chindatagroup.com/media/news/533.html",
        "publisher": "Chindata",
        "source_date": "2026-07-02",
        "observed_date": dc["knowledge_cutoff"][:10],
        "classification": "PRIMARY_OPERATOR_PUBLICATION",
        "supports": dc["supports"][0],
        "does_not_establish": " ".join(dc["does_not_support"]),
    }]
    sodium_evidence = [
        {
            "evidence_id": record["record_id"],
            "title": f"{sodium['title']}: {record['publisher']} record dated {record['event_date']}",
            "source_url": record["url"],
            "publisher": record["publisher"],
            "source_date": record["event_date"],
            "observed_date": record["knowledge_date"],
            "classification": record["source_type"].upper().replace(" ", "_"),
            "supports": record["accepted_support"],
            "does_not_establish": record["does_not_support"],
        }
        for record in sodium["records"]
    ]
    return {
        "800vdc": {
            "case_id": dc["case_id"],
            "title": "800V DC Data Center Power Architecture",
            "canonical_url": f"{BASE_URL}/cases/800vdc/",
            "question": "Has 800V DC power architecture moved from proposal to independently attributable field deployment?",
            "answer": "One attributable operator record supports one commercial SST-to-800VDC deployment; independent validation, replication, and industry adoption remain unresolved.",
            "current_state": dc["current_bounded_state"],
            "as_of": dc["knowledge_cutoff"],
            "last_material_change": "2026-09-20",
            "evidence": dc_evidence,
            "counter_evidence": [
                {"title": "Vertiv practical path to 800 VDC", "state": "PLANNED_DEPLOYMENT", "reason": "Future commercialization and pilots do not establish field operation."},
                {"title": "Siemens and Reinhausen DC power solutions", "state": "UNDER_DEVELOPMENT", "reason": "Development for future deployment does not establish field operation."},
            ],
            "unknowns": dc["unknowns"] + ["Industry-scale adoption."],
            "search_provenance": [{"run_date": dc["knowledge_cutoff"], "query_count": 4, "source_count": 9, "deep_review_count": 1, "boundary": "One narrow L1 field-deployment verification; no general 800V research was authorized."}],
            "history": [{"date": "2026-09-20", "previous_state": "R5_FIELD_DEPLOYED_NOT_ESTABLISHED", "new_state": "R5_ARCHITECTURE_FIELD_DEPLOYMENT_EVIDENCE_ACCEPTED_SINGLE_INSTANCE", "triggering_evidence": dc_evidence[0]["evidence_id"], "why": "Human review accepted one attributable operator record for one named commercial deployment."}],
        },
        "sodium-ion-bess": {
            "case_id": sodium["case_id"],
            "title": "Sodium-Ion BESS Commercialization",
            "canonical_url": f"{BASE_URL}/cases/sodium-ion-bess/",
            "question": sodium["decision_question"],
            "answer": "Product launch and cooperation evidence is supported; a named delivered and commissioned customer system is not established at the stated cutoff.",
            "current_state": "NAMED_COMMISSIONED_SITE_NOT_ESTABLISHED",
            "as_of": sodium["knowledge_cutoff"],
            "last_material_change": sodium["knowledge_cutoff"],
            "evidence": sodium_evidence,
            "counter_evidence": [{"title": "Commissioned-site threshold", "state": "NO_QUALIFYING_RECORD_ACCEPTED", "reason": "The reviewed record contains plans, launches, and cooperation evidence but no accepted named customer commissioning record."}],
            "unknowns": sodium["next_transition_evidence"],
            "search_provenance": [{"run_date": sodium["knowledge_cutoff"], "boundary": sodium["scope"], "source_types": "Manufacturer and counterparty public records; no independent customer field dataset accepted."}],
            "history": [{"date": sodium["knowledge_cutoff"], "previous_state": "NO_PUBLIC_BASELINE", "new_state": "NAMED_COMMISSIONED_SITE_NOT_ESTABLISHED", "triggering_evidence": "SE-BESS-SODIUM-001-v0.1", "why": "The frozen v0.1 record separated product and agreement evidence from delivery, commissioning, and operating history."}],
        },
    }


def main() -> None:
    cases = build_cases()
    for slug, case in cases.items():
        public = {key: case[key] for key in ["case_id", "title", "canonical_url", "question", "answer", "current_state", "as_of", "last_material_change", "evidence", "counter_evidence", "unknowns", "search_provenance", "history"]}
        write_json(f"cases/{slug}/index.json", public)
        write_case_yaml(slug, public)
        for key in ["evidence", "counter_evidence", "unknowns", "search_provenance"]:
            write_json(f"cases/{slug}/{key}.json", public[key])
        write_json(f"cases/{slug}/state_history.json", public["history"])
        readme = (
            f"# {case['title']}\n\nCanonical record: {case['canonical_url']}\n\n"
            "Files in this directory are public verification exports. `index.json`, `case.yaml`, and the component JSON files are generated by `scripts/export_public_records.py`.\n"
        )
        for path in [ROOT / "cases" / slug / "README.md", ROOT / "docs" / "cases" / slug / "README.md"]:
            path.write_text(readme, encoding="utf-8")
        for record in case["evidence"]:
            route = ROOT / "e" / record["evidence_id"]
            route.mkdir(parents=True, exist_ok=True)
            write_json(f"e/{record['evidence_id']}/index.json", {**record, "parent_case": case["case_id"], "parent_case_url": case["canonical_url"], "canonical_url": f"{BASE_URL}/e/{record['evidence_id']}/"})
            content = evidence_html(case, record)
            (route / "index.html").write_text(content, encoding="utf-8")
            docs_route = ROOT / "docs" / "e" / record["evidence_id"]
            docs_route.mkdir(parents=True, exist_ok=True)
            (docs_route / "index.html").write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
